alter table public.students
add column if not exists reg_no bigint;

alter table public.students
add column if not exists admission_id uuid;

create unique index if not exists students_reg_no_unique
on public.students (reg_no)
where reg_no is not null;

create unique index if not exists students_admission_id_unique
on public.students (admission_id)
where admission_id is not null;

create table if not exists public.admissions (
  id uuid primary key default gen_random_uuid(),
  reg_no bigint generated by default as identity unique,
  applicant_name text not null,
  nationality text not null default 'Indian',
  date_of_birth date not null,
  age integer not null check (age between 4 and 18),
  gender text not null default '',
  father_guardian_name text not null,
  emergency_contact_no text not null,
  parent_contact_no text not null,
  city text not null default '',
  address text not null default '',
  school_college text not null default '',
  parent_aadhaar_no text not null default '',
  time_slot text not null default '',
  join_date date not null default current_date,
  fees_paid boolean not null default false,
  amount_paid numeric(10, 2) not null default 0,
  batsman_style text not null default '',
  bowling_styles text[] not null default '{}',
  ready_to_start boolean not null default false,
  consent_accepted boolean not null default false,
  terms_accepted boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.registration_counters (
  counter_name text primary key,
  next_reg_no bigint not null
);

insert into public.registration_counters (counter_name, next_reg_no)
values (
  'admissions',
  greatest(
    coalesce((select max(reg_no) + 1 from public.admissions), 1001),
    1001
  )
)
on conflict (counter_name) do nothing;

create or replace function public.sync_student_from_admission()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.students (
    reg_no,
    admission_id,
    name,
    age,
    time_slot,
    join_date,
    fees_paid,
    amount_paid,
    renewals,
    discontinued,
    discontinued_at,
    added_by,
    updated_by
  )
  values (
    new.reg_no,
    new.id,
    new.applicant_name,
    new.age,
    new.time_slot,
    new.join_date,
    new.fees_paid,
    new.amount_paid,
    '{}',
    false,
    null,
    'Admission Form',
    'Admission Form'
  );

  return new;
end;
$$;

drop trigger if exists admissions_create_student on public.admissions;

create trigger admissions_create_student
after insert on public.admissions
for each row
execute function public.sync_student_from_admission();

create or replace function public.submit_admission_form(
  p_applicant_name text,
  p_nationality text,
  p_date_of_birth date,
  p_age integer,
  p_gender text,
  p_father_guardian_name text,
  p_emergency_contact_no text,
  p_parent_contact_no text,
  p_city text,
  p_address text,
  p_school_college text,
  p_parent_aadhaar_no text,
  p_time_slot text,
  p_join_date date,
  p_fees_paid boolean,
  p_amount_paid numeric,
  p_batsman_style text,
  p_bowling_styles text[],
  p_ready_to_start boolean,
  p_consent_accepted boolean,
  p_terms_accepted boolean
)
returns table(id uuid, reg_no bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_reg_no bigint;
begin
  if not p_consent_accepted or not p_terms_accepted then
    raise exception 'Please accept the required consent and terms.';
  end if;

  insert into public.registration_counters (counter_name, next_reg_no)
  values ('admissions', 1001)
  on conflict (counter_name) do nothing;

  update public.registration_counters
  set next_reg_no = next_reg_no + 1
  where counter_name = 'admissions'
  returning next_reg_no - 1 into v_reg_no;

  return query
  insert into public.admissions (
    reg_no,
    applicant_name,
    nationality,
    date_of_birth,
    age,
    gender,
    father_guardian_name,
    emergency_contact_no,
    parent_contact_no,
    city,
    address,
    school_college,
    parent_aadhaar_no,
    time_slot,
    join_date,
    fees_paid,
    amount_paid,
    batsman_style,
    bowling_styles,
    ready_to_start,
    consent_accepted,
    terms_accepted
  )
  values (
    v_reg_no,
    p_applicant_name,
    p_nationality,
    p_date_of_birth,
    p_age,
    p_gender,
    p_father_guardian_name,
    p_emergency_contact_no,
    p_parent_contact_no,
    p_city,
    p_address,
    p_school_college,
    p_parent_aadhaar_no,
    p_time_slot,
    p_join_date,
    p_fees_paid,
    p_amount_paid,
    p_batsman_style,
    coalesce(p_bowling_styles, '{}'),
    p_ready_to_start,
    p_consent_accepted,
    p_terms_accepted
  )
  returning admissions.id, admissions.reg_no;
end;
$$;

create or replace function public.peek_next_admission_reg_no()
returns table(next_reg_no bigint)
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.registration_counters (counter_name, next_reg_no)
  values ('admissions', 1001)
  on conflict (counter_name) do nothing;

  return query
  select rc.next_reg_no
  from public.registration_counters rc
  where rc.counter_name = 'admissions';
end;
$$;

alter table public.admissions enable row level security;

drop policy if exists "admissions_public_insert" on public.admissions;
create policy "admissions_public_insert"
on public.admissions
for insert
to anon, authenticated
with check (true);

drop policy if exists "admissions_authenticated_read" on public.admissions;
create policy "admissions_authenticated_read"
on public.admissions
for select
to authenticated
using (true);

grant execute on function public.submit_admission_form(
  text, text, date, integer, text, text, text, text, text, text, text, text,
  text, date, boolean, numeric, text, text[], boolean, boolean, boolean
) to anon, authenticated;

grant execute on function public.peek_next_admission_reg_no() to anon, authenticated;
